/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface KnowledgeEdge {
  'relationType' : string,
  'toId' : bigint,
  'fromId' : bigint,
}
export interface Memory {
  'id' : bigint,
  'isGlobal' : boolean,
  'text' : string,
  'concepts' : Array<string>,
  'timestamp' : bigint,
  'principalId' : string,
  'memoryType' : string,
}
export interface PersonalityProfile {
  'analytical' : number,
  'friendliness' : number,
  'curiosity' : number,
}
export interface Rule {
  'id' : bigint,
  'effect' : string,
  'timestamp' : bigint,
  'condition' : string,
}
export interface TimelineEntry {
  'id' : bigint,
  'personalitySnapshot' : PersonalityProfile,
  'event' : string,
  'timestamp' : bigint,
}
export interface UserProfile {
  'personality' : PersonalityProfile,
  'username' : string,
  'avatarUrl' : string,
  'principalId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addKnowledgeEdge' : ActorMethod<[bigint, bigint, string], undefined>,
  'addMemory' : ActorMethod<[string, string, Array<string>, boolean], bigint>,
  'addRule' : ActorMethod<[string, string], bigint>,
  'addTimelineEntry' : ActorMethod<[string, PersonalityProfile], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMemory' : ActorMethod<[bigint], boolean>,
  'deleteRule' : ActorMethod<[bigint], boolean>,
  'exportGlobalData' : ActorMethod<[], string>,
  'exportUserData' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKnowledgeEdges' : ActorMethod<[], Array<KnowledgeEdge>>,
  'getMemories' : ActorMethod<[boolean], Array<Memory>>,
  'getPersonality' : ActorMethod<[], PersonalityProfile>,
  'getRules' : ActorMethod<[], Array<Rule>>,
  'getSentryAvatar' : ActorMethod<[], string>,
  'getTimeline' : ActorMethod<[], Array<TimelineEntry>>,
  'getUserMemories' : ActorMethod<[], Array<Memory>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importGlobalData' : ActorMethod<[string], boolean>,
  'importUserData' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSentryAvatar' : ActorMethod<[string], undefined>,
  'setUserAvatar' : ActorMethod<[string], undefined>,
  'setUsername' : ActorMethod<[string], undefined>,
  'updatePersonality' : ActorMethod<[number, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];